<?php

/**
 * PluginKintaiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginKintaiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginKintaiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginKintai');
    }
}